#-*- coding: utf-8 -*-

{
	"name": "Vit marketing sph Inherited",
	"version": "1.0", 
	"depends": [
		'base','vit_marketing','stock','vit_marketing_inquery','vit_marketing_rab'
		,'vit_marketing_sph'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing sph module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/squence.xml",
		"views/marketing_sph.xml",
		"data/paperformat.xml",
		"report/marketing_sph_report.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}