#-*- coding: utf-8 -*-

{
	"name": "Vit marketing rab Inherited",
	"version": "1.0", 
	"depends": [
		'base','stock','vit_marketing','account'
		,'vit_marketing_rab'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing rab module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/squence.xml",
		"data/vit.master_rab_line.csv",
		"views/marketing_rab.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}