#-*- coding: utf-8 -*-

{
	"name": "Vit marketing sph",
	"version": "1.0", 
	"depends": [
		'base','stock','vit_marketing','vit_marketing_inherit','vit_marketing_inquery','vit_marketing_inquery_inherit','vit_marketing_rab','vit_marketing_rab_inherit'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing sph module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/marketing_sph.xml",
		"view/boq_sph_line.xml",
		"view/term_sph_line.xml",
		"view/doc_sph_line.xml",
		# "view/partner.xml",
		# "view/inquery.xml",
		# "view/uom.xml",
		# "view/rab.xml",
		# "view/product_sph.xml",
		# "report/marketing_sph.xml",
		# "report/boq_sph_line.xml",
		# "report/term_sph_line.xml",
		# "report/doc_sph_line.xml",
		# "report/partner.xml",
		# "report/inquery.xml",
		# "report/uom.xml",
		# "report/rab.xml",
		# "report/product_sph.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}