#-*- coding: utf-8 -*-

{
	"name": "Vit ppic material plan Inherited",
	"version": "1.0", 
	"depends": [
		'base','stock','vit_ppic','vit_ppic_inherit',
		'vit_ppic_schedule', 'vit_pr_inherit',
		'vit_ppic_workorder',
		'vit_procurement_inherit',
		'vit_inventory_inherit'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit ppic material plan module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		'data/squence.xml',
		'view/material_plan.xml',
		'view/material_plan_lane.xml',
		'wizard/wizard_material_plan_inherit.xml',
		'wizard/wizard_material_plan_booking_all_inherit.xml',
		'wizard/wizard_material_plan_all_inherit.xml'
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}
