#-*- coding: utf-8 -*-

{
	"name": "Vit accounting tpb Inherited",
	"version": "1.0", 
	"depends": [
		'base', 'stock', 'vit_marketing_jo', 'vit_marketing_po', 'om_account_accountant','vit_procurement_po'
		, 'account', 'vit_accounting_tpb'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit accounting tpb module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		'data/squence.xml',
		'view/accounting_tpb.xml',
		'view/accounting_tpb_line.xml',
		'view/doc_tpb_line.xml',
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}