#-*- coding: utf-8 -*-

{
	"name": "Vit ppic material request Inherited",
	"version": "1.0", 
	"depends": [
		'base','stock','vit_marketing_jo','vit_ppic',
		'vit_ppic_material_request',
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit ppic material request module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/squence.xml",
		"view/ppic_material_request.xml",
		"view/material_request_line.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}
