#-*- coding: utf-8 -*-

{
	"name": "Vit ppic material booking",
	"version": "1.0", 
	"depends": [
		'base','stock','vit_marketing_jo','vit_ppic'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit ppic material booking module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/ppic_material_booking.xml",
		"view/ppic_material_booking_line.xml",
		# "view/product_jo.xml",
		# "view/product_temp.xml",
		# "report/ppic_material_booking.xml",
		# "report/ppic_material_booking_line.xml",
		# "report/product_jo.xml",
		# "report/product_temp.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}