#-*- coding: utf-8 -*-

{
	"name": "Vit accounting tpb",
	"version": "1.0", 
	"depends": [
		'base', 'stock', 'vit_marketing_jo', 'vit_marketing_po', 'om_account_accountant','account','vit_procurement_po',
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit accounting tpb module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/accounting_tpb.xml",
		# "view/product.xml",
		# "view/jo.xml",
		"view/accounting_tpb_line.xml",
		# "view/uom.xml",
		# "view/product_jo.xml",
		# "view/ResPartner.xml",
		# "view/procurement_po.xml",
		"view/doc_tpb_line.xml",
		],
	"installable": True,
	"auto_install": False,
	"application": True,
}