#-*- coding: utf-8 -*-

{
	"name": "Vit marketing rab",
	"version": "1.0", 
	"depends": [
		'base','vit_marketing','vit_marketing_inherit','vit_marketing_inquery','vit_marketing_inquery_inherit','account'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit marketing rab module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/marketing_rab.xml",
		# "view/marketing_inquery.xml",
		"view/rab_line.xml",
		# "view/product.xml",
		"view/product_line.xml",
		# "view/uom.xml",
		"view/master_rab_line.xml",
		# "view/account.xml",
		"view/rab_product_line.xml",
		# "report/marketing_rab.xml",
		# "report/marketing_inquery.xml",
		# "report/rab_line.xml",
		# "report/product.xml",
		# "report/product_line.xml",
		# "report/uom.xml",
		# "report/master_rab_line.xml",
		# "report/account.xml",
		# "report/rab_product_line.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}