#-*- coding: utf-8 -*-

{
	"name": "Vit ppic material plan",
	"version": "1.0", 
	"depends": [
		'base','stock',
		'vit_ppic','vit_ppic_inherit',
		'vit_marketing_jo','vit_marketing',
		'vit_ppic_schedule',
		'vit_ppic_material_booking',
		'vit_inventory'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit ppic material plan module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/material_plan.xml",
		# "view/product.xml",
		# "view/lot.xml",
		"view/material_plan_lane.xml",
		# "view/uom.xml",
		# "view/product_jo.xml",
		# "report/material_plan.xml",
		# "report/product.xml",
		# "report/lot.xml",
		# "report/material_plan_lane.xml",
		# "report/uom.xml",
		# "report/product_jo.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}