#-*- coding: utf-8 -*-

{
	"name": "Vit ppic material booking Inherited",
	"version": "1.0", 
	"depends": [
		'base','stock','vit_marketing_jo','vit_ppic'
		,'vit_ppic_material_booking', 'vit_ppic_material_plan_inherit'
	],
	"author": "My Company",
	"category": "Utility",
	"website": "richard.angga51@gmail.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit ppic material booking module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": ['security/ir.model.access.csv',
	'data/location.xml',
	'data/seq.xml',
	'view/booking.xml',
	'view/wizard_booking.xml',
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}
